version: '3.9'
name: tp1
services:
  book_boundary:
    container_name: book_boundary
    image: boundary:latest
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
      - LOGGING_LEVEL=INFO
      - OUTPUT_EXCHANGE=books
      - BOUNDARY_TYPE=book
    networks:
      - test_net

  review_boundary:
    container_name: review_boundary
    image: boundary:latest
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
      - LOGGING_LEVEL=INFO
      - OUTPUT_EXCHANGE=reviews
      - BOUNDARY_TYPE=review
    networks:
      - test_net

  client:
    container_name: client
    image: client:latest
    volumes:
      - ./datasets:/datasets
    environment:
      - PYTHONUNBUFFERED=1
      - BOOK_BOUNDARY_PORT=12345
      - BOOK_BOUNDARY_IP=book_boundary
      - REVIEW_BOUNDARY_PORT=12345
      - REVIEW_BOUNDARY_IP=review_boundary
      - LOGGING_LEVEL=INFO
    depends_on:
      - book_boundary
    networks:
      - test_net    
      
  book_filter_by_category_computers:
    image: book_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FILTER_BY_FIELD="categories"
      - FILTER_BY_VALUES=["Computers"]
      - INPUT_QUEUES={"books_filter_by_category_computers":"books"}
      - OUTPUT_QUEUES=["computers_books"]
      - OUTPUT_EXCHANGES=[]
    networks: 
      - test_net

  filter_books_by_year_2000_2023:
    image: book_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FILTER_BY_FIELD="year"
      - FILTER_BY_VALUES=[2000,2023]
      - INPUT_QUEUES={"computers_books":""}
      - OUTPUT_QUEUES=["2000_2023_computers_books"]
      - OUTPUT_EXCHANGES=[]
    networks: 
      - test_net

  filter_books_by_title_distributed:
    image: book_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FILTER_BY_FIELD="title"
      - FILTER_BY_VALUES=["distributed"]
      - INPUT_QUEUES={"2000_2023_computers_books":""}
      - OUTPUT_QUEUES=["2000_2023_computers_distributed_books"]
      - OUTPUT_EXCHANGES=[]
    networks: 
      - test_net

  author_decades_counter:
    image: author_decades_counter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUES={"authors_books_test":"books"}
      - OUTPUT_QUEUES=["query2_result"]
    networks: 
      - test_net

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24