name: tp1
services:
  book_boundary:
    container_name: book_boundary
    image: boundary:latest
    environment:
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
      - LOGGING_LEVEL=INFO
    entrypoint: python3 /main.py book_q
    networks:
      - test_net
  review_boundary:
    container_name: review_boundary
    image: boundary:latest
    environment:
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
      - LOGGING_LEVEL=INFO
    entrypoint: python3 /main.py review_q
    networks:
      - test_net
  client:
    container_name: client
    image: client:latest
    environment:
      - BOOK_BOUNDARY_PORT=12345
      - BOOK_BOUNDARY_IP=book_boundary
      - LOGGING_LEVEL=INFO
    depends_on:
      - book_boundary
    entrypoint: python3 /main.py
    networks:
      - test_net
    volumes:
      - ./datasets:/datasets

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

  