version: '3.9'
name: tp1
services:
  book_boundary:
    container_name: book_boundary
    image: boundary:latest
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
      - LOGGING_LEVEL=INFO
    networks:
      - test_net

  client:
    container_name: client
    image: client:latest
    volumes:
      - ./datasets:/datasets
    environment:
      - PYTHONUNBUFFERED=1
      - BOOK_BOUNDARY_PORT=12345
      - BOOK_BOUNDARY_IP=book_boundary
      - LOGGING_LEVEL=INFO
    depends_on:
      - book_boundary
    networks:
      - test_net    
      
  book_filter_by_category:
    container_name: book_filter_by_category
    image: book_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - FILTER_BY_FIELD="categories"
      - FILTER_BY_VALUES=["Fiction"]
      - INPUT_QUEUES={"books_filter_by_category":"books"}
      - OUTPUT_QUEUES=["fiction_books"]
      - OUTPUT_EXCHANGES=[]
    networks: 
      - test_net

  filter_books_by_year:
    container_name: filter_books_by_year
    image: book_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - FILTER_BY_FIELD="year"
      - FILTER_BY_VALUES=["2001","2005", "2009"]
      - INPUT_QUEUES={"fiction_books":""}
      - OUTPUT_QUEUES=["fiction_books_filtered_by_year"]
      - OUTPUT_EXCHANGES=[]
    networks: 
      - test_net

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24