version: '3.9'
name: tp1
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  server:
    container_name: server
    build: ./server    
    volumes:
      - ./server:/server
      - ./common:/server/common
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG    
    depends_on:
      - rabbitmq
  
  worker:
    container_name: worker
    build: ./worker
    volumes:
      - ./worker:/server
      - ./common:/server/common
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - FILTER_BY_FIELD="category"
      - FILTER_BY_VALUES=["fiction"]
      - INPUT_QUEUES={"books_filter_by_category":"books"}
      - OUTPUT_QUEUES=["fiction_books"]
      - OUTPUT_EXCHANGES=[]
    depends_on:
      - rabbitmq

  filter_books_by_year:
    container_name: filter_books_by_year
    build: ./worker
    volumes:
      - ./worker:/server
      - ./common:/server/common
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - FILTER_BY_FIELD="year"
      - FILTER_BY_VALUES=["1951","1869"]
      - INPUT_QUEUES={"fiction_books":""}
      - OUTPUT_QUEUES=["fiction_books_filtered_by_year"]
      - OUTPUT_EXCHANGES=[]
    depends_on:
      - rabbitmq